version: "3"
services:
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        ports:
        - 27017:27017
        command: --smallfiles
    app:
        image: springio/lvurl
        ports:
        - 8080:8080
        links:
        - mongodb
    prometheus:
        image: prom/prometheus:0.18.0
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - '9090:9090'

    node-exporter:
        image: prom/node-exporter:v0.17.0
        ports:
            - '9100:8080'

    cadvisor-exporter:
        container_name: "cadvisor-exporter"
        image: google/cadvisor
        ports:
          - "9200:8080"
        volumes:
          - "/:/rootfs:ro"
          - "/var/run:/var/run:rw"
          - "/sys:/sys:ro"
          - "/var/lib/docker/:/var/lib/docker:ro"